### ISSUE TITLE
bug: replace resource started failing; name is a required property

### ISSUE THREAD

**Issue by stephenratz** [jenssegers/chef-file#26]
I noticed that the replace resource calls in my cookbook started failing. I'm using version 2.2.1. Is there something I'm doing wrong or is there an issue with the resource? See screenshot.

![patch_supermarket_cookbook_replace_resource_name_attribute_error](https://user-images.githubusercontent.com/22688055/47591773-6887ed00-d936-11e8-8c3a-00300351913e.png)

**Comment by stephenratz** [comment]
It's possible this issue is caused by the patch cookbook not being in the local supermarket I'm using. Please disregard.

**Comment by VBobik** [comment]
Did You solve this issue ?

**Comment by stephenratz** [comment]
There’s a problem with your module. I had rewrite and create my own local custom resource. I’m not looking at the code right now. Your module broke when I upgraded my version of Chef. It had to do with how the parameters were declared and called. I think the parameters had to be referenced with new_resource.parameter_name or something close to that.

**Comment by andrey-iliyov** [comment]
have to be like this:

```
resource_name :append_line
actions :run
default_action :run

property :name, :name_property => true, :kind_of => String, :required => true
property :file, :kind_of => String
property :path, :kind_of => String
property :line, :kind_of => String, :required => true

action :run do

	file_path = new_resource.file || new_resource.path || new_resource.name

	# Line matching regex
	regex = /^#{Regexp.escape(new_resource.line)}$/

	# Check if file matches the regex
	if ::File.read(file_path) !~ regex
		# Calculate file hash before changes
		before = Digest::SHA256.file(file_path).hexdigest

		# Do changes
		file = Chef::Util::FileEdit.new(file_path)
		file.insert_line_if_no_match(regex, new_resource.line)
		file.write_file

		# Notify file changes
		if Digest::SHA256.file(file_path).hexdigest != before
			Chef::Log.info "+ #{new_resource.line}"
			new_resource.updated_by_last_action(true)
		end

		# Remove backup file
		::File.delete(file_path + ".old") if ::File.exist?(file_path + ".old")
	end
end
```

**Comment by andrey-iliyov** [comment]
I will create a pull request soon
